set dotenv-load := true
set shell := ["bash", "-uc"]

run_select:
    pwd
    while read program; do \
        just \
        --dotenv-path ./projects/$program/.env \
        projects/run_complete; \
    done < projects/to_run.txt