set dotenv-load := true
set shell := ["bash", "-cu"]

OUTPUT_DIR := env("OUTPUT_DIR", "output")
CALLGRAPH := env("CALLGRAPH", "callgraph")
CODE_DIR := env("CODE_DIR", "code")

clone:
    bash scripts/clone.sh {{CODE_DIR}}

process_raw PROGRAM:
    python scripts/process_raw.py --program {{PROGRAM}}

extract_source PROGRAM:
    python scripts/extract_source.py --program {{PROGRAM}}

process_graph PROGRAM:
    python scripts/process_graph.py --program {{PROGRAM}}

run PROGRAM:
    just process_raw {{PROGRAM}}
    just extract_source {{PROGRAM}}
    just process_graph {{PROGRAM}}
