set dotenv-load := true
set shell := ["bash", "-cu"]

OUTPUT_DIR := env("OUTPUT_DIR", "output")
CALLGRAPH := env("CALLGRAPH", "callgraph")

process_raw PROGRAM:
    python scripts/process_raw.py --program {{PROGRAM}} 2>&1 | tee "{{OUTPUT_DIR}}/process_raw_{{PROGRAM}}.log"
